version: 2.1
executors:
  default:
    docker:
    - image: cimg/go:1.18.0

aliases:
- &restore_cache
  restore_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
- &save_cache
  save_cache:
    key: go-mod-v1-{{ checksum "go.sum" }}
    paths:
      - "/go/pkg/mod"

jobs:
  check-style:
    executor:
      name: default
    steps:
    - checkout
    - *restore_cache
    - run: make check-style
    - *save_cache

  test:
    executor:
      name: default
    steps:
    - checkout
    - *restore_cache
    - run: make setup-test test
    - *save_cache
    
  push-docker-pr:
    executor:
      name: default
    steps:
    - checkout
    - setup_remote_docker
    - run: make build-image
    - run: |
        set -e
        set -u
        export TAG="${CIRCLE_SHA1:0:7}"
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        docker tag mattermost/mattermost-cloud-database-factory:test mattermost/mattermost-cloud-database-factory:$TAG
        docker push mattermost/mattermost-cloud-database-factory:$TAG

  push-docker:
    executor:
      name: default
    steps:
    - checkout
    - setup_remote_docker
    - run: make build-image
    - run: |
        set -e
        set -u
        if [[ -z "${CIRCLE_TAG:-}" ]]; then
          echo "Pushing lastest for $CIRCLE_BRANCH..."
          TAG=latest
        else
          echo "Pushing release $CIRCLE_TAG..."
          TAG="$CIRCLE_TAG"
        fi
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        docker tag mattermost/mattermost-cloud-database-factory:test mattermost/mattermost-cloud-database-factory:$TAG
        docker push mattermost/mattermost-cloud-database-factory:$TAG

  scan-image:
    docker:
    - image: registry.gitlab.com/gitlab-org/security-products/analyzers/klar:latest
      environment:
        GIT_STRATEGY: none
        CI_APPLICATION_REPOSITORY: mattermost/mattermost-cloud-database-factory
        CLAIR_DB_CONNECTION_STRING: "postgresql://postgres:password@localhost:5432/postgres?sslmode=disable&statement_timeout=60000"
        DOCKERFILE_PATH: "build/Dockerfile"
    - image: arminc/clair-db:latest
    steps:
    - checkout
    - run: |
        export CI_APPLICATION_TAG="${CIRCLE_SHA1:0:7}"
        export DOCKER_USER=$DOCKER_USERNAME
        /analyzer run
    - store_artifacts:
        path: gl-container-scanning-report.json
        destination: security-scan

  release:
    executor: default
    steps:
      - checkout
      - run:
          command: |
            sudo apt update && sudo apt install hub git
            GO111MODULE=on go get k8s.io/release/cmd/release-notes
            make release
workflows:
  version: 2
  ci-build:
    jobs:
    - check-style
    - test
    - push-docker-pr:
        context: matterbuild-docker
        requires:
        - check-style
        - test
    - scan-image:
        context: matterbuild-docker
        requires:
        - push-docker-pr
  master-build:
    jobs:
    - check-style:
        filters:
          branches:
            only:
            - master
    - test:
        filters:
          branches:
            only:
            - master
    - push-docker:
          context: matterbuild-docker
          requires:
          - check-style
          - test
          filters:
            branches:
              only:
              - master
  tag-builds:
    jobs:
    - check-style:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - test:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - push-docker:
        context: matterbuild-docker
        requires:
        - check-style
        - test
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/

  publish-github-release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
